version: '3.8'

services:
  leguidedurootard:
    container_name: leguidedurootard01
    build: .
    networks:
      - bridge
    volumes:
      - ./src/db/:/app/db/

networks:
  bridge:
    driver: bridge
